### ISSUE TITLE
[Feature Request] Support for Installation/Update/Running via Sketch Runner

### ISSUE THREAD

**Issue by luxlogica** [matej-marjanovic/6Spiral-Sketch-Plugin#2]
Please add support for plugin installation and updates via **[Sketch Runner](https://sketchrunner.com)**. It would also be wonderful if we could *run the plugin* from the Sketch Runner interface. There is a [Developer Page](https://sketchrunner.com/developers.html) in the Sketch Runner website, which teaches plugin developers how to do all this quite easily.

The plugin is amazing. Keep up the good work - it's truly appreciated! :-)

**Comment by matej-marjanovic** [comment]
Hi @luxlogica.  Thanks for posting the issue. 👍 6Spiral is now supported by Sketch Runner.
