### ISSUE TITLE
How do I change the color of the line?

### ISSUE THREAD

**Issue by lynndylanhurley** [matej-marjanovic/6Spiral-Sketch-Plugin#4]
When I select the line I don't get the path / fill options that are normally visible for lines.

The only option I see on the right is 'radius':

![Screen Shot 2019-04-06 at 12 31 31 PM](https://user-images.githubusercontent.com/468037/55673029-f7931c80-5867-11e9-8695-207a57e8f553.png)

**Comment by matej-marjanovic** [comment]
Hi @lynndylanhurley, thanks for submitting this. On the left panel, you need to select the "SPIRALshape" parent layer to be able to change the border color.

![Screen Recording 2019-04-08 at 04 17 PM](https://user-images.githubusercontent.com/2822227/55762998-2bae3f00-5a1a-11e9-877c-2cf0699cefcc.gif)
